#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.datasource.url=jdbc:mysql://localhost:3306/remark_system?serverTimezone=GMT%2B8&characterEncoding=utf-8
#
#spring.datasource.username=root
#
#spring.datasource.password=123456
#
#mybatis-plus.mapper-locations=classpath:com/label/core/mapper/xml/*.xml
#
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081


spring:
  mail:
    host: smtp.qq.com
    username: 1933320948@qq.com
    password: xkmhtwlwupngbjaa
    properties:
      mail:
        stmp:
          ssl:
            enable: true


  redis:
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默
    port: 6379
    host: 192.168.121.130
    connect-timeout: 6000ms

  profiles:
    active: dev
  application:
    name: server-core
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/remark_system?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/label/core/mapper/xml/*.xml
logging:
  level:
    root: debug







